# Imports

In [1]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import re

from src import gradio_utils

from src.parse_labeling import parse_labeled_file
from src.wikidata_utils import translate_term, wikidata_gradio

# Read File

## Concat ARC

benchmark_name = 'arc_ai2_comparison_90'

file_name = f'labeled_files/{benchmark_name}.txt'
csv_name = f'manual_compare/{benchmark_name}_FULL.csv'
label_df, or_df = parse_labeled_file(file_name, csv_name)

label_df.shape, or_df.shape

file_name = 'manual_compare/arc_ai2_comparison_91_200_FULL.csv'
or_df_more = pd.read_csv(file_name)
or_df_more.shape

display(label_df.head(2))
display(or_df.head(2))
display(or_df_more.head(2))

new_df = pd.concat([
    or_df[or_df_more.columns],
    or_df_more,
], ignore_index=True)
print(new_df.shape)
new_df.tail(3)

new_df.to_csv('manual_compare/arc_ai2_train_top_200_FULL.csv')

## Claude Version

new_df = pd.read_csv('manual_compare/claude_vers_comparison_FULL.csv')
new_df.head(3)

## GSM8K

In [ ]:
file_name = f'labeled_files/gsm8k_comparison_200.txt'
csv_name = f'manual_compare/gsm8k_comparison_200_FULL.csv'
old_label_df, new_df = parse_labeled_file(file_name, csv_name)

old_label_df.reset_index(inplace=True, drop=True)
new_df.reset_index(inplace=True, drop=True)

print((new_df['option 1'] == old_label_df['option 1']).sum())
print((new_df['option 2'] == old_label_df['option 2']).sum())

old_label_df.shape, new_df.shape

In [ ]:
new_df.index, old_label_df.index

In [ ]:
display(old_label_df.head(2))
display(new_df.head(2))

## MMLU

In [22]:
new_df = pd.read_csv('manual_compare/mmlu_test_each_90_FULL.csv')
print(new_df.shape)
new_df.head(2)

(157, 5)

,original,model 1,model 2,option 1,option 2
0,<question>Find the degree for the given field ...,claude_thinking_v2,gemini_pro_think_v1,<question>מצאו את המעלה עבור הרחבת השדה הנתונה...,<question>מצאו את המעלה עבור הרחבת השדה הנתונה...
1,<question>Statement 1 | If a finite group has ...,gemini_pro_think_v1,claude_thinking_v2,"<question>טענה 1 | אם לחבורה סופית יש סדר n, א...",<question>היגד 1 | אם חבורה סופית היא מסדר n א...

In [23]:
# Concat the train which was labeled
mmlu_train = pd.read_csv('labeled_files/mmlu_train_labeled_gradio.csv')
mmlu_train.fillna('', inplace=True)
mmlu_train = mmlu_train[(mmlu_train['gold'] != '') | (mmlu_train['rating'] != '')]
print(mmlu_train.shape)
mmlu_train.head(2)

(20, 6)

,text_column,new_text_column,gold,rating,model 1,model 2
0,<question>The cyclic subgroup of Z_24 generate...,Option 1:\n<question>הסדר של התת-חבורה הציקלית...,,1,gemini_pro_think_v1,claude_v1_refine
1,<question>Statement 1 | The symmetric group S_...,Option 1:\n<question>טענה 1 | החבורה הסימטרית ...,,1,gemini_pro_think_v1,claude_v1_refine

# Create UI

In [12]:
# save_to = 'labeled_files/arc_ai_labeled_gradio.csv'
# save_to = 'labeled_files/claude_vers_labeled_gradio.csv'
# save_to = 'labeled_files/gsm8k_labeled_gradio.csv'
save_to = 'labeled_files/mmlu_test_labeled_gradio.csv'

# save_to = 'labeled_files/mmlu_train_labeled_gradio.csv'
# save_to = 'labeled_files/mmlu_train_half_labeled_gradio.csv'

def enter_to_text(x):
    return f"""Option 1:
{x['option 1']}

Option 2:
{x['option 2']}"""

labeled_df = pd.DataFrame()
labeled_df['text_column'] = new_df['original']
labeled_df['new_text_column'] = new_df.apply(enter_to_text, axis=1)
labeled_df['gold'] = ''
labeled_df['rating'] = ''

# maybe add?
labeled_df['model 1'] = new_df['model 1']
labeled_df['model 2'] = new_df['model 2']
print(labeled_df.shape)
labeled_df.head(2)

# Check matching and add already lebeled gold and rating
print(labeled_df.index, old_label_df.index)

for i in range(old_label_df.shape[0]):
    if not old_label_df['option 1'].iloc[i] in labeled_df['new_text_column'].iloc[i]:
        print(i)
        break
else:
    print('hey!')

# Add the already-labeled gold and rating for the top arc samples
labeled_df.loc[:, ['gold', 'rating']] = old_label_df[['gold', 'rating']]
display(labeled_df.head(2))

# Concat with train-labeled mmlu
labeled_df = pd.concat([labeled_df, mmlu_train], ignore_index=True)
print(labeled_df.shape)
labeled_df.tail(2)

labeled_df.to_csv(save_to, index=False)

In [13]:
labeled_df = pd.read_csv(save_to)

In [14]:
labeled_df = labeled_df.fillna('')

In [6]:
# This is the GSM8K server
server = gradio_utils.run_annotator(labeled_df, save_to, ' - MMLU benchamrk')
wiki_server = wikidata_gradio()

* Running on local URL:  http://127.0.0.1:7860
* Running on public URL: https://ac5d10145c073712c7.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
* Running on local URL:  http://127.0.0.1:7861
* Running on public URL: https://698c3be33e0481a2c3.gradio.live

This share link expires in 1 week. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
server.close()

In [198]:
wiki_server.close()

Closing server running on port: 7862